### ISSUE TITLE
Fails to play custom discs

### ISSUE THREAD

**Issue by ryleu** [HooferDevelops/url-music-discs#7]
When I try to play discs I get an exception in the logs and nothing happens. Here's my log: https://mclo.gs/4X8fGZH

I am on Fedora Linux 39, on mc version 1.20.1 with no other mods

**Comment by ryleu** [comment]
error:
```
[00:22:17] [Sound engine/ERROR]: Error executing task on Sound executor
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4234.method_19719()" because "$$0" is null
	at net.minecraft.class_4224.method_19643(class_4224.java:138) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_19755(class_1140.java:467) ~[client-intermediary.jar:?]
	at net.minecraft.class_4235$class_4236.method_19737(class_4235.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_4238.method_19765(class_4238.java:42) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

deobfuscated:
```
[00:24:47] [Sound engine/ERROR]: Error executing task on Sound executor
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.sound.AudioStream.getFormat()" because "$$0" is null
	at net.minecraft.client.sound.Source.setStream(Source.java:138) ~[client-intermediary.jar:?]
	at net.minecraft.client.sound.SoundSystem.method_19755(SoundSystem.java:467) ~[client-intermediary.jar:?]
	at net.minecraft.client.sound.Channel$SourceManager.method_19737(Channel.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.client.sound.SoundExecutor.waitForStop(SoundExecutor.java:42) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by ryleu** [comment]
using this url: https://www.youtube.com/watch?v=c5wulic5wsU

**Comment by Erokaution** [comment]
As a workaround, try to rip the audio from the youtube video and upload to Discord.
At least some youtube vids seem broken at the moment. But Discord CDN links still work (...at least for another month or two until Discord makes all their CDN links temporary. [Nudge nudge](https://github.com/HooferDevelops/url-music-discs/issues/8).

**Comment by ryleu** [comment]
Is there a way to allow other URLs? Like a config option? I can just add that to my modpack and then host my own music disks.

**Comment by ryleu** [comment]
Same issue on this URL: 

https://cdn.discordapp.com/attachments/1182908803063234580/1185485325171171358/Quirky_Worky_Song_c5wulic5wsU.webm

![image](https://github.com/HooferDevelops/url-music-discs/assets/69326171/5c4c46b8-2318-486b-bf2a-912a27111505)

**Comment by ryleu** [comment]
to be clear this issue occurs both in singleplayer and multiplayer & with no mods except url music discs

**Comment by Plompi** [comment]
Should be fixed with #21
